name: 'Crates Release'
description: 'Releases a Rust crate to crates.io'
inputs:
  working-directory:
    description: 'Directory to run steps in'
    required: false
    default: './'
  crates-token:
    description: 'Publish token for crates.io'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: Update rust
      run: rustup update
      shell: bash

    - name: Install protobuf compiler
      run: sudo apt-get install -y protobuf-compiler
      shell: bash

    - name: Cargo login
      env:
        CRATES_TOKEN: ${{ inputs.crates-token }}
      run: cargo login ${{ env.CRATES_TOKEN }}
      shell: bash

    - name: Cargo publish
      run: cargo publish --no-verify
      shell: bash
      working-directory: ${{ inputs.working-directory }}

